version: '3.5'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn frontend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume_prod:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume_prod:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data_prod:
  static_volume_prod:
